version: 2.1

commands:
  setup-python-env:
    steps:
      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Set up Python
          command: uv python install
      - run:
          name: Install project dependencies
          command: uv sync --all-extras --dev

jobs:
  defillama-protocols:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - setup-python-env
      - run:
          name: DefiLlama Protocol TVL
          command: uv run opdata pulls defillama_protocol_tvl
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: DefiLlama Historical Chain TVL
          command: uv run opdata pulls defillama_historical_chain_tvl
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}

  daily-uploads-other-tasks:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - setup-python-env
      - run:
          name: L2Beat
          command: uv run opdata pulls l2beat
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: DefiLlama Stablecoins
          command: uv run opdata pulls defillama_stablecoins
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: DefiLlama DEX Volume, Fees, Revenue
          command: uv run opdata pulls defillama_dexs_fees_revenue
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: GitHub Analytics
          command: uv run opdata pulls github_analytics
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: GrowThePie Chain Summary
          command: uv run opdata pulls growthepie_chain_summary
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}
      - run:
          name: DefiLlama Stablecoins BQ
          command: uv run opdata pulls defillama_stablecoins_bq
          environment:
            OPLABS_RUNTIME: "gha"
            OPLABS_ENV: "prod"
            OP_ANALYTICS_VAULT: ${OP_ANALYTICS_VAULT}

workflows:
  version: 2
  # daily-api-uploads:
  #   triggers:
  #     - schedule:
  #         cron: "15 3 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - defillama-protocols:
  #         context: op-analytics
  #     - daily-uploads-other-tasks:
  #         context: op-analytics

  manual:
    when:
      equal: [<< pipeline.trigger_source >>, "api"]
    jobs:
      - defillama-protocols:
          context: op-analytics
      - daily-uploads-other-tasks:
          context: op-analytics
