ending_patterns_to_filter:
  - "-borrowed"
  - "-vesting"
  - "-staking"
  - "-pool2"
  - "-treasury"
  - "-cex"

exact_patterns_to_filter:
  - "treasury"
  - "borrowed"
  - "staking"
  - "pool2"
  - "polygon-bridge-&-staking"

categories_to_filter:
  - "CEX"
  - "Chain"

alignment_dict:
  Metis: "OP Stack fork"
  Blast: "OP Stack fork"
  Mantle: "OP Stack fork"
  Zircuit: "OP Stack fork"
  RSS3: "OP Stack fork"
  Rollux: "OP Stack fork"
  Ancient8: "OP Stack fork"
  Manta: "OP Stack fork"
  Cyber: "OP Chain"
  Mint: "OP Chain"
  Ham: "OP Chain"
  Polynomial: "OP Chain"
  Lisk: "OP Chain"
  BOB: "OP Chain"
  Mode: "OP Chain"
  World Chain: "OP Chain"
  Base: "OP Chain"
  Kroma: "OP Chain"
  Boba: "OP Chain"
  Fraxtal: "OP Chain"
  Optimism: "OP Chain"
  Shape: "OP Chain"
  Zora: "OP Chain"
  Ink: "OP Chain"
  Swell: "Op Chain"

token_data:
  # Native Assets
  - token: "ETH"
    token_category: "Native Asset"
  - token: "WETH"
    token_category: "Native Asset"
  - token: "SOL"
    token_category: "Native Asset"

  # Wrapped Assets
  - token: "wBTC"
    token_category: "Wrapped Assets"
  - token: "cbBTC"
    token_category: "Wrapped Assets"
  - token: "MBTC"
    token_category: "Wrapped Assets"

  # Liquid Staking
  - token: "stETH"
    token_category: "Liquid Staking"
  - token: "wstETH"
    token_category: "Liquid Staking"
  - token: "sfrxETH"
    token_category: "Liquid Staking"
  - token: "rETH"
    token_category: "Liquid Staking"
  - token: "mETH"
    token_category: "Liquid Staking"
  - token: "swETH"
    token_category: "Liquid Staking"
  - token: "frxETH"
    token_category: "Liquid Staking"
  - token: "ETHX"
    token_category: "Liquid Staking"
  - token: "lsETH"
    token_category: "Liquid Staking"
  - token: "oETH"
    token_category: "Liquid Staking"
  - token: "SUPEROETHB"
    token_category: "Liquid Staking"
  - token: "WSUPEROETHB"
    token_category: "Liquid Staking"
  - token: "TETH"
    token_category: "Liquid Staking"
  - token: "OSETH"
    token_category: "Liquid Staking"
  - token: "cbETH"
    token_category: "Liquid Staking"

  # Liquid Restaking
  - token: "rsETH"
    token_category: "Liquid Restaking"
  - token: "ezETH"
    token_category: "Liquid Restaking"
  - token: "rswETH"
    token_category: "Liquid Restaking"
  - token: "EBTC"
    token_category: "Liquid Restaking"
  - token: "LBTC"
    token_category: "Liquid Restaking"
  - token: "cmETH"
    token_category: "Liquid Restaking"
  - token: "WRSETH"
    token_category: "Liquid Restaking"
  - token: "WEETH.BASE"
    token_category: "Liquid Restaking"

  # Stablecoins
  - token: "USDC"
    token_category: "Stablecoins"
  - token: "USDT"
    token_category: "Stablecoins"
  - token: "FDUSD"
    token_category: "Stablecoins"
  - token: "PYUSD"
    token_category: "Stablecoins"
  - token: "TUSD"
    token_category: "Stablecoins"
  - token: "DAI"
    token_category: "Stablecoins"
  - token: "USDE"
    token_category: "Stablecoins"
  - token: "USDD"
    token_category: "Stablecoins"
  - token: "FRAX"
    token_category: "Stablecoins"
  - token: "EURC"
    token_category: "Stablecoins"
  - token: "AGEUR"
    token_category: "Stablecoins"
  - token: "USDS"
    token_category: "Stablecoins"
  - token: "USDB"
    token_category: "Stablecoins"
  - token: "DOLA"
    token_category: "Stablecoins"
  - token: "SUSDE"
    token_category: "Stablecoins"
  - token: "USD0++"
    token_category: "Stablecoins"
  - token: "USD0"
    token_category: "Stablecoins"
  - token: "SUSD"
    token_category: "Stablecoins"
  - token: "CRVUSD"
    token_category: "Stablecoins"
  - token: "USDC+"
    token_category: "Stablecoins"
  - token: "USDZ"
    token_category: "Stablecoins"
  - token: "STAR"
    token_category: "Stablecoins"
  - token: "USDBC"
    token_category: "Stablecoins"
  - token: "USD+"
    token_category: "Stablecoins"
  - token: "CDXUSD"
    token_category: "Stablecoins"
  - token: "HYUSD"
    token_category: "Stablecoins"
  - token: "EURS"
    token_category: "Stablecoins"
  - token: "AXLEUROC"
    token_category: "Stablecoins"

  # Solana Liquid Staking
  - token: "MSOL"
    token_category: "Liquid Staking"
  - token: "JUPSOL"
    token_category: "Liquid Staking"
  - token: "BNSOL"
    token_category: "Liquid Staking"
  - token: "LAINESOL"
    token_category: "Liquid Staking"
  - token: "STSOL"
    token_category: "Liquid Staking"
  - token: "STRONGSOL"
    token_category: "Liquid Staking"
  - token: "HUBSOL"
    token_category: "Liquid Staking"
  - token: "PATHSOL"
    token_category: "Liquid Staking"
  - token: "STEPSOL"
    token_category: "Liquid Staking"
  - token: "EDGESOL"
    token_category: "Liquid Staking"
  - token: "JITOSOL"
    token_category: "Liquid Staking"
  - token: "DSOL"
    token_category: "Liquid Staking"
  - token: "BONKSOL"
    token_category: "Liquid Staking"
  - token: "VSOL"
    token_category: "Liquid Staking"
  - token: "HSOL"
    token_category: "Liquid Staking"

  # Solana Liquid Restaking
  - token: "SSOL"
    token_category: "Liquid Restaking"
  - token: "BBSOL"
    token_category: "Liquid Restaking"
