name: OP Stack Chain Revenue Pulls

on:
  schedule:
      - cron: '24,54 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Display System Info
        run: |
          free -h
          df -h

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      
      - name: Check cache status
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"

      - name: Check for Pipfile.lock
        run: |
          if [ -f "Pipfile.lock" ]; then
            echo "Pipfile.lock found"
            cat Pipfile.lock
          else
            echo "Pipfile.lock not found"
            ls -la
          fi

      - name: Install pipenv
        run: |
          python -m pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv install --dev
      
      - name: Check virtualenv
        run: |
          pipenv --venv

      - name: Generate py files
        working-directory: op_chains_tracking
        run: |
          pipenv run jupyter nbconvert --to python l2_revenue_tracking.ipynb

      - name: Run File
        working-directory: op_chains_tracking
        run: |
          pipenv run python l2_revenue_tracking.py
        env:
          IS_RUNNING_LOCAL: ${{ secrets.IS_RUNNING_LOCAL }}
          BQ_APPLICATION_CREDENTIALS: ${{ secrets.BQ_APPLICATION_CREDENTIALS }}
          BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}

      - name: Pull changes
        run: |
          git pull origin main

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "GH Action Update - Chain Revenue" -a
            echo "push=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}