name: Run OP Distribution Tracking Scripts

# Controls when the workflow will run
on:
  # Run on a schedule - Once per day at 12:10 am
  schedule:
      - cron: '10 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Set up Python and Node.js
      - name: Set up Python and Node.js
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        # Set max space to see if this helps with timeouts
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        # Update the Node.js version to 16
          node-version: '16'

      - name: Install pipenv
        run: |
          python -m pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv install --dev
      
      # Some dependencies just don't run
      - name: Install Missing Python dependencies
        run: |
          python -m pip install --upgrade pip pandas numpy
          pip install -U kaleido asyncio aiohttp nest_asyncio subgrounds jupyter nbconvert plotly aiohttp_retry python-dotenv

  # Generate .py files for each notebook
      - name: Generate py files
        working-directory: op_rewards_tracking
        run: |
          jupyter nbconvert --to python pull_dune_data.ipynb
          jupyter nbconvert --to python optimism_incentives_app_net_flows.ipynb
          jupyter nbconvert --to python op_incentives_program_attribution.ipynb
          jupyter nbconvert --to python op_incentive_program_summary.ipynb          
          
  # Runs a single command using the runners shell

  # Dune Data
      - name: Pull OP Usage Data in Dune
        working-directory: op_rewards_tracking
        run: pipenv run python pull_dune_data.py
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

  # OP App Flows
      - name: Update OP App Net Flows
        working-directory: op_rewards_tracking
        run: python optimism_incentives_app_net_flows.py

  # Incentives Attribution
      - name: Update OP Incentives Attribution
        working-directory: op_rewards_tracking
        run: python op_incentives_program_attribution.py
  
  # Incentives Program Summary
      - name: Update OP Incentives Summary
        working-directory: op_rewards_tracking
        run: python op_incentive_program_summary.py
 
        
  # commit_results:
    # if: ${{ always() }} #Always runs even if prior jobs fail - so that one bad job doesn't f everything up.
    # needs: build #[build, app_fees, op_summer, total_tvl_flow]
    # runs-on: ubuntu-latest
    # steps:
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      
      # Commit and push output images
      # https://github.com/orgs/community/discussions/26672
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
          if [-z "$(git status --porcelain)"]; then
             # echo "::set-output name=push::false"
             echo "push=false" >> $GITHUB_OUTPUT
          else
             git commit -m "GH Action Update" -a
             # echo "::set-output name=push::true"
             echo "push=true" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
